#imports

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

#read csv

In [ ]:
dff = pd.read_csv('/content/1315431420272_wine.csv')

In [ ]:
dff.shape

(178, 15)

#droping categorical column

In [ ]:
dff['class_name'].value_counts()

class_name
Grignolino    71
Barolo        59
Barbera       48
Name: count, dtype: int64

In [ ]:
df = dff.iloc[:,2:]

In [ ]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280,proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

# Step 1 - Apply standard scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df = sc.fit_transform(df)

# Step 2 - Find Covariance Matrix

# Step 3 - Finding EV and EVs

In [ ]:
covariance_matrix = np.cov(df, rowvar=False)
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)
print('Covariance Matrix:\n shape', len(covariance_matrix))

Covariance Matrix:
 shape 13

In [ ]:
pc = eigen_vectors[0:5]
len(pc[0])

13

In [ ]:
transformed_df = np.dot(df,pc.T)
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2','PC3','PC4','PC5'])
#new_df['class_name'] = dff['class_name'].values
new_df.head()

        PC1       PC2       PC3       PC4       PC5
0 -0.658708 -0.352319 -1.215578  1.935357  1.049028
1 -0.625556 -1.551017  0.624217  0.935570  0.746135
2  1.171673 -0.424399 -1.116935  0.957300 -0.593912
3  0.622881  0.186926 -0.926507  1.533924  0.502178
4  0.257468  0.458052 -1.268378 -0.527380  0.211018

In [ ]:
new_df.shape

(178, 5)

In [ ]:
rec = np.dot(new_df,pc)

In [ ]:
rec.shape

(178, 13)

In [ ]:
rec = pd.DataFrame(rec)

In [ ]:
rec.sample(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12
136,-0.902090,1.239600,1.101432,-0.651718,-0.234227,0.688703,-0.623110,0.294530,-0.677304,-0.294234,-0.194288,-1.919144,0.245766
8,0.335355,-0.210081,-1.324709,-0.204419,-0.196327,-0.429562,0.864683,-0.002189,0.413982,-0.112398,0.148302,0.399357,0.127917
113,-0.151257,-0.632410,0.987245,0.245406,-0.903568,-0.158126,0.112457,0.187951,-0.500449,0.059808,0.727485,-0.601740,-0.140054
125,0.276390,-0.041765,-0.353061,0.379869,-0.598662,0.089909,0.375320,0.006018,0.440873,-0.118737,0.060378,0.114297,-0.047525
100,0.310495,-0.076843,-2.029646,-0.591412,0.214393,-0.338615,0.683962,0.166000,-0.318902,0.106756,0.828235,-0.095363,-0.075969

In [ ]:
reconstruction_error = np.mean((df- rec)**2)
print(reconstruction_error)

0.6864959564720536