#import

In [188]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [189]:
df = pd.read_csv('/content/cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

#we need to encode fuel and owner

#**ONE HOT ENCODING USING PANDAS**

In [190]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int).sample(5)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
2069,BMW,140000,1300000,0,1,0,0,0,0,1,0,0
6569,BMW,8500,5500000,0,1,0,0,1,0,0,0,0
2078,Nissan,36000,800000,0,1,0,0,1,0,0,0,0
2910,Hyundai,25000,570000,0,0,0,1,1,0,0,0,0
2441,Hyundai,50000,210000,0,0,0,1,0,0,1,0,0

In [191]:
pd.get_dummies(df,columns=['fuel','owner']).shape[1]

12

#ignoring the first column(retundent)

In [192]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True,dtype=int).sample(5)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
4587,Maruti,80000,140000,0,0,1,0,1,0,0
125,Maruti,40000,360000,0,0,1,0,1,0,0
1759,Maruti,140000,450000,0,0,1,0,0,0,0
5675,Maruti,15000,300000,0,0,1,0,1,0,0
3829,Maruti,188000,70000,0,0,1,1,0,0,0

In [193]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True).shape[1]

10

#ONE HOT ENCODING USING SKLEARN

In [194]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [195]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [196]:
from sklearn.preprocessing import OneHotEncoder

In [197]:
ohe = OneHotEncoder(drop='first',dtype=int,sparse_output=False)
#sparse_output=False What it does:
#Tells the encoder to return a standard, dense NumPy array instead of a compressed sparse matrix.

In [198]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [199]:
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [200]:
print(type(x_train[['brand','km_driven']]),type(x_train_new))

<class 'pandas.core.frame.DataFrame'> <class 'numpy.ndarray'>

In [201]:
x_train_new = pd.DataFrame(np.hstack((x_train[['brand','km_driven']],x_train_new)))

In [202]:
x_train_new.sample(5)

             0       1  2  3  4  5  6  7  8
2876      Tata   95500  1  0  0  0  1  0  0
4118    Maruti   38817  1  0  0  0  0  0  0
4674  Mahindra   40000  1  0  0  0  0  0  0
5208  Mahindra   70000  1  0  0  0  1  0  0
1586    Maruti  120000  1  0  0  0  1  0  0

#OneHotEncoding with Top Categories

In [203]:
counts = df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [204]:
df['brand'].nunique()
threshold = 100

In [205]:
replace = counts[counts <= threshold].index

In [206]:
df['brand'].head()

0     Maruti
1      Skoda
2      Honda
3    Hyundai
4     Maruti
Name: brand, dtype: object

In [207]:
pd.get_dummies(df['brand'].replace(replace, 'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3234,0,0,0,0,0,0,1,0,0,0,0,0,0
1193,0,0,0,0,0,1,0,0,0,0,0,0,0
2992,0,0,0,0,0,0,0,0,0,0,0,0,1
3526,0,0,0,0,0,0,1,0,0,0,0,0,0
3304,0,0,0,0,1,0,0,0,0,0,0,0,0